#ifndef CO2_DETECT_SHARED_CONSTANTS_H
#define CO2_DETECT_SHARED_CONSTANTS_H

#define CO2_PROJECT_NAME "co2-detect"

#define CO2_VER_MAJOR "1"
#define CO2_VER_MINOR "0"
#define CO2_VER_PATCH "0"

#define CO2_VER_CHANNEL "dev"

#define CO2_VER_STRING CO2_VER_MAJOR "." CO2_VER_MINOR "." CO2_VER_PATCH
#define CO2_VER_VERBOSE CO2_VER_STRING "-" CO2_VER_CHANNEL

#endif //CO2_DETECT_SHARED_CONSTANTS_H